"""Project-used mpmath 1.3 interfaces; real powers are checked by callers.

These declarations are not executable code. Arithmetic overloads distinguish real
and complex values; the reference uses real exponentiation only on positive bases.
"""
from contextlib import AbstractContextManager
from typing import Callable, overload

class mpf:
    def __new__(cls, value: int | str | mpf | mpc = ..., imag: int | mpf = ...) -> mpf: ...
    @property
    def real(self) -> mpf: ...
    @property
    def imag(self) -> mpf: ...
    @overload
    def __add__(self, other: int | mpf) -> mpf: ...
    @overload
    def __add__(self, other: mpc) -> mpc: ...
    @overload
    def __radd__(self, other: int | mpf) -> mpf: ...
    @overload
    def __radd__(self, other: mpc) -> mpc: ...
    @overload
    def __sub__(self, other: int | mpf) -> mpf: ...
    @overload
    def __sub__(self, other: mpc) -> mpc: ...
    @overload
    def __rsub__(self, other: int | mpf) -> mpf: ...
    @overload
    def __rsub__(self, other: mpc) -> mpc: ...
    @overload
    def __mul__(self, other: int | mpf) -> mpf: ...
    @overload
    def __mul__(self, other: mpc) -> mpc: ...
    @overload
    def __rmul__(self, other: int | mpf) -> mpf: ...
    @overload
    def __rmul__(self, other: mpc) -> mpc: ...
    @overload
    def __truediv__(self, other: int | mpf) -> mpf: ...
    @overload
    def __truediv__(self, other: mpc) -> mpc: ...
    @overload
    def __rtruediv__(self, other: int | mpf) -> mpf: ...
    @overload
    def __rtruediv__(self, other: mpc) -> mpc: ...
    @overload
    def __pow__(self, other: int | mpf) -> mpf: ...
    @overload
    def __pow__(self, other: mpc) -> mpc: ...
    @overload
    def __rpow__(self, other: int | mpf) -> mpf: ...
    @overload
    def __rpow__(self, other: mpc) -> mpc: ...
    def __neg__(self) -> mpf: ...
    def __pos__(self) -> mpf: ...
    def __abs__(self) -> mpf: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __lt__(self, other: int | float | mpf) -> bool: ...
    def __le__(self, other: int | float | mpf) -> bool: ...
    def __gt__(self, other: int | float | mpf) -> bool: ...
    def __ge__(self, other: int | float | mpf) -> bool: ...

class mpc:
    def __new__(cls, value: int | str | mpf | mpc = ..., imag: int | mpf = ...) -> mpc: ...
    @property
    def real(self) -> mpf: ...
    @property
    def imag(self) -> mpf: ...
    def __add__(self, other: int | mpf | mpc) -> mpc: ...
    def __radd__(self, other: int | mpf | mpc) -> mpc: ...
    def __sub__(self, other: int | mpf | mpc) -> mpc: ...
    def __rsub__(self, other: int | mpf | mpc) -> mpc: ...
    def __mul__(self, other: int | mpf | mpc) -> mpc: ...
    def __rmul__(self, other: int | mpf | mpc) -> mpc: ...
    def __truediv__(self, other: int | mpf | mpc) -> mpc: ...
    def __rtruediv__(self, other: int | mpf | mpc) -> mpc: ...
    def __pow__(self, other: int | mpf | mpc) -> mpc: ...
    def __rpow__(self, other: int | mpf | mpc) -> mpc: ...
    def __neg__(self) -> mpc: ...
    def __abs__(self) -> mpf: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...

class MPContext:
    mpf: type[mpf]
    mpc: type[mpc]
    pi: mpf
    eps: mpf
    inf: mpf
    nan: mpf
    j: mpc
    dps: int
    prec: int
    def workdps(self, dps: int) -> AbstractContextManager[None]: ...
    def isfinite(self, value: int | mpf | mpc) -> bool: ...
    def nstr(self, value: int | mpf | mpc, n: int = ...) -> str: ...
    def re(self, value: int | mpf | mpc) -> mpf: ...
    @overload
    def conj(self, value: mpf) -> mpf: ...
    @overload
    def conj(self, value: mpc) -> mpc: ...
    def factorial(self, value: int) -> mpf: ...
    def log10(self, value: int | mpf) -> mpf: ...
    def hyp1f1(self, a: int, b: int, z: mpf) -> mpf: ...
    @overload
    def diff(self, function: Callable[[mpf], mpf], point: mpf, order: int = ..., *, direction: int = ...) -> mpf: ...
    @overload
    def diff(self, function: Callable[..., mpf], point: tuple[mpf, ...], order: tuple[int, ...], *, direction: int = ...) -> mpf: ...
    @overload
    def exp(self, value: int | mpf) -> mpf: ...
    @overload
    def exp(self, value: mpc) -> mpc: ...
    @overload
    def sin(self, value: int | mpf) -> mpf: ...
    @overload
    def sin(self, value: mpc) -> mpc: ...
    @overload
    def cos(self, value: int | mpf) -> mpf: ...
    @overload
    def cos(self, value: mpc) -> mpc: ...
    @overload
    def sqrt(self, value: int | mpf) -> mpf: ...
    @overload
    def sqrt(self, value: mpc) -> mpc: ...
    @overload
    def log(self, value: int | mpf) -> mpf: ...
    @overload
    def log(self, value: mpc) -> mpc: ...

mp: MPContext
