[package]
name = "p10-avx-scheduled-endpoint"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[features]
default = []
n256 = []
n384-prep = []
n384-h32 = ["n384-prep"]
n384-h64 = ["n384-prep"]
n384-piecewise-common = []
n384-piecewise = ["n384-prep", "n384-piecewise-common"]
n384-piecewise-cadv33 = ["n384-prep", "n384-piecewise-common"]
n384-m512-piecewise-cadv33 = ["n384-prep", "n384-piecewise-common"]
n512-m512-piecewise-cadv33 = ["n384-prep", "n384-piecewise-common"]

[dependencies]
nsbu-benchmarks = { path = "../../../../crates/nsbu-benchmarks" }
nsbu-solver = { path = "../../../../crates/nsbu-solver" }
sha2 = "=0.10.9"
stats_alloc = "=0.1.10"
