"""Generate Rust gauge metadata from authoritative pressure-mean JSON files."""
from argparse import ArgumentParser
import hashlib
import json
from pathlib import Path


def rust_string(value: str) -> str:
    """Use a raw Rust literal for arbitrary decimal strings."""
    return f'r#"{value}"#'


def option(value: str | None) -> str:
    """Render an optional decimal string without rounding."""
    return 'None' if value is None else f'Some({rust_string(value)})'


def emit(paths: list[Path]) -> str:
    """Emit deterministic typed metadata while retaining hashes of exact input bytes."""
    lines=['// @generated by reference/generate_pressure_gauge_rust.py; raw JSON remains authoritative.']
    data=[]
    for index,path in enumerate(paths):
        raw=path.read_bytes(); report=json.loads(raw)
        if report.get('status')!='pressure-mean-diagnostic-complete' or len(report.get('estimates',[]))!=10:
            raise ValueError(f'{path}: require one complete ten-estimate diagnostic')
        elapsed={'0':0,'1/16384':64,'1/8192':128}[report['profiles'][0]['time']]
        digest=', '.join(str(byte) for byte in hashlib.sha256(raw).digest())
        lines += [f'const SHA_{index}: [u8; 32] = [{digest}];',f'const ESTIMATES_{index}: [GaugeEstimate; 10] = [']
        for row in report['estimates']:
            lines.append('    GaugeEstimate { axial_panels: %d, radial_panels: %d, precision: %d, raw_mean: %s },' %
                         (row['axial_panels'],row['radial_squared_panels'],row['precision'],rust_string(row['mean'])))
        changes=report['changes']; precision=', '.join(rust_string(value) for value in changes['precision_differences'])
        lines += ['];',f'''const CHANGES_{index}: GaugeChanges = GaugeChanges {{
    coarse_to_middle: {rust_string(changes['coarse_to_middle'])},
    middle_to_fine: {rust_string(changes['middle_to_fine'])},
    axial_only_to_fine: {rust_string(changes['axial_only_to_fine'])},
    radial_only_to_fine: {rust_string(changes['radial_only_to_fine'])},
    precision_differences: [{precision}],
    maximum_precision_to_finest_quadrature_ratio: {option(changes['maximum_precision_to_finest_quadrature_ratio'])},
    finest_mean: {rust_string(changes['finest_mean'])},
    relative_finest_quadrature_change: {option(changes['relative_finest_quadrature_change'])},
}};''',f'const DATA_{index}: GaugeData = GaugeData {{ elapsed: {elapsed}, sha256: SHA_{index}, estimates: &ESTIMATES_{index}, changes: CHANGES_{index} }};']
        data.append(f'DATA_{index}')
    lines.append(f'const DATA: [GaugeData; {len(data)}] = [{", ".join(data)}];')
    return '\n'.join(lines)+'\n'


def main() -> None:
    parser=ArgumentParser();parser.add_argument('artifacts',nargs='+',type=Path);parser.add_argument('--output',required=True,type=Path)
    args=parser.parse_args();args.output.write_text(emit(args.artifacts),encoding='utf-8')

if __name__=='__main__': main()
