"""Generate Rust gauge metadata from authoritative pressure-mean JSON files."""

import argparse
import hashlib
from pathlib import Path
from typing import cast
from tools.json_types import Json, array_value, decode, object_value, string_value


def integer(value: Json) -> int:
    """Decode an integer while rejecting booleans and floating-point values."""
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError("Expected a JSON integer")
    return value


def optional_string(value: Json) -> str | None:
    """Decode a nullable decimal string."""
    return None if value is None else string_value(value)


def rust_string(value: str) -> str:
    """Use a raw Rust literal for arbitrary decimal strings."""
    return f'r#"{value}"#'


def option(value: str | None) -> str:
    """Render an optional decimal string without rounding."""
    return "None" if value is None else f"Some({rust_string(value)})"


def read_report(path: Path) -> tuple[bytes, dict[str, Json]]:
    """Decode the complete producer shape before emitting any output."""
    raw = path.read_bytes()
    report = dict(object_value(decode(raw.decode())))
    estimates = array_value(report.get("estimates"))
    if (
        string_value(report.get("status")) != "pressure-mean-diagnostic-complete"
        or len(estimates) != 10
    ):
        raise ValueError(f"{path}: require one complete ten-estimate diagnostic")
    return raw, report


def emit_estimates(index: int, report: dict[str, Json]) -> list[str]:
    """Retain every raw mean and its actual profile settings."""
    lines = [f"const ESTIMATES_{index}: [GaugeEstimate; 10] = ["]
    for item in array_value(report["estimates"]):
        row = object_value(item)
        lines.append(
            "    GaugeEstimate { axial_panels: %d, radial_panels: %d, precision: %d, raw_mean: %s },"
            % (
                integer(row.get("axial_panels")),
                integer(row.get("radial_squared_panels")),
                integer(row.get("precision")),
                rust_string(string_value(row.get("mean"))),
            )
        )
    lines.append("];")
    return lines


def emit_changes(index: int, report: dict[str, Json]) -> str:
    """Keep arithmetic and both quadrature directions separate."""
    changes = object_value(report["changes"])
    precision = ", ".join(
        rust_string(string_value(value))
        for value in array_value(changes.get("precision_differences"))
    )
    return f"""const CHANGES_{index}: GaugeChanges = GaugeChanges {{
    coarse_to_middle: {rust_string(string_value(changes.get('coarse_to_middle')))},
    middle_to_fine: {rust_string(string_value(changes.get('middle_to_fine')))},
    axial_only_to_fine: {rust_string(string_value(changes.get('axial_only_to_fine')))},
    radial_only_to_fine: {rust_string(string_value(changes.get('radial_only_to_fine')))},
    precision_differences: [{precision}],
    maximum_precision_to_finest_quadrature_ratio: {option(optional_string(changes.get('maximum_precision_to_finest_quadrature_ratio')))},
    finest_mean: {rust_string(string_value(changes.get('finest_mean')))},
    relative_finest_quadrature_change: {option(optional_string(changes.get('relative_finest_quadrature_change')))},
}};"""


def emit_one(index: int, path: Path) -> list[str]:
    """Emit one hash-bound exact-clock artifact projection."""
    raw, report = read_report(path)
    profiles = array_value(report["profiles"])
    first = object_value(profiles[0])
    elapsed = {"0": 0, "1/16384": 64, "1/8192": 128}[string_value(first.get("time"))]
    digest = ", ".join(str(byte) for byte in hashlib.sha256(raw).digest())
    lines = [f"const SHA_{index}: [u8; 32] = [{digest}];"]
    lines.extend(emit_estimates(index, report))
    lines.append(emit_changes(index, report))
    lines.append(
        f"const DATA_{index}: GaugeData = GaugeData {{ elapsed: {elapsed}, sha256: SHA_{index}, estimates: &ESTIMATES_{index}, changes: CHANGES_{index} }};"
    )
    return lines


def emit(paths: list[Path]) -> str:
    """Emit deterministic metadata for the complete fixed clock sequence."""
    lines = [
        "// @generated by reference/generate_pressure_gauge_rust.py; raw JSON remains authoritative."
    ]
    for index, path in enumerate(paths):
        lines.extend(emit_one(index, path))
    data = ", ".join(f"DATA_{index}" for index in range(len(paths)))
    lines.append(f"const DATA: [GaugeData; {len(paths)}] = [{data}];")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write generated source only after every artifact validates."""
    parser = argparse.ArgumentParser()
    parser.add_argument("artifacts", nargs="+", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    output = cast(Path, args.output)
    paths = cast(list[Path], args.artifacts)
    output.write_text(emit(paths), encoding="utf-8")


if __name__ == "__main__":
    main()
