[package]
name = "p10-n512-m512-parallel-fft-timing"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
nsbu-benchmarks = { path = "../../../../crates/nsbu-benchmarks" }
nsbu-solver = { path = "../../../../crates/nsbu-solver" }
stats_alloc = "=0.1.10"
sha2 = { version = "=0.10.9", default-features = false, features = ["force-soft"] }
